---
- name: Normalize architecture
  ansible.builtin.set_fact: # noqa: var-naming[no-role-prefix]
    system_arch: >-
      {{
        'arm64'
        if ansible_facts['architecture'] == 'aarch64'
        else 'amd64'
        if ansible_facts['architecture'] == 'x86_64'
        else ansible_facts['architecture']
      }}
    system_dist: "{{ ansible_facts['distribution_release'] | lower }}"

- name: Set user variables
  ansible.builtin.set_fact: # noqa: var-naming[no-role-prefix]
    user_home: "{{ ansible_facts['env'].HOME }}"
    dev_user: "{{ ansible_facts['env'].USER | default(ansible_user) | default('root') }}"
